/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import BaseDatos.DbConnection;
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario : EmersonQH
 */
public class Login extends javax.swing.JFrame {
    //Para la posicion del mouse
    int xMouse, yMouse;
    //venta de menu principal
    MenuPrincipal mp= new MenuPrincipal();
    //conexion a la base de datos
    Connection db = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Login() {
        initComponents(); 
        setBackground (new Color(0,0,0,0));
        //conxecion db
        db = DbConnection.ConnectionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound4 = new Interfaces.PanelRound();
        panelRound2 = new Interfaces.PanelRound();
        exitBtn = new Interfaces.PanelRound();
        textExit = new javax.swing.JLabel();
        panelRound1 = new Interfaces.PanelRound();
        TituloApp = new javax.swing.JLabel();
        TextUser = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        TextPassword = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();
        ButtonIngreso = new javax.swing.JButton();
        RestaurarPassword = new javax.swing.JLabel();
        panelRound3 = new Interfaces.PanelRound();

        panelRound4.setRoundBottomLeft(70);
        panelRound4.setRoundBottomRight(70);
        panelRound4.setRoundTopLeft(70);
        panelRound4.setRoundTopRight(70);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(240, 240, 240));
        panelRound2.setRoundTopLeft(70);
        panelRound2.setRoundTopRight(70);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(240, 240, 240));
        exitBtn.setRoundBottomLeft(70);
        exitBtn.setRoundBottomRight(70);
        exitBtn.setRoundTopLeft(70);
        exitBtn.setRoundTopRight(70);

        textExit.setBackground(java.awt.Color.white);
        textExit.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        textExit.setForeground(new java.awt.Color(153, 153, 153));
        textExit.setText("X");
        textExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textExitMouseExited(evt);
            }
        });
        exitBtn.add(textExit);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, -1));

        panelRound1.setBackground(new java.awt.Color(240, 240, 240));
        panelRound1.setRoundBottomLeft(70);
        panelRound1.setRoundBottomRight(70);
        panelRound1.setRoundTopLeft(70);
        panelRound1.setRoundTopRight(70);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloApp.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TituloApp.setForeground(new java.awt.Color(0, 0, 0));
        TituloApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloApp.setText("ReqWizards App");
        TituloApp.setToolTipText("");
        panelRound1.add(TituloApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 200, 40));

        TextUser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextUser.setForeground(new java.awt.Color(0, 0, 0));
        TextUser.setText("Usuario:");
        TextUser.setToolTipText("");
        panelRound1.add(TextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        Usuario.setBackground(new java.awt.Color(255, 255, 255));
        Usuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Usuario.setText("Ejemplo: AUT-0000");
        Usuario.setToolTipText("");
        Usuario.setBorder(null);
        Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuarioMousePressed(evt);
            }
        });
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        panelRound1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 280, 30));
        Usuario.getAccessibleContext().setAccessibleName("");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        panelRound1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, 20));

        TextPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TextPassword.setForeground(new java.awt.Color(0, 0, 0));
        TextPassword.setText("Contraseña:");
        TextPassword.setToolTipText("");
        panelRound1.add(TextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        panelRound1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 280, 20));

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setForeground(new java.awt.Color(204, 204, 204));
        Password.setText("********");
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        panelRound1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 280, 30));

        ButtonIngreso.setBackground(new java.awt.Color(119, 29, 75));
        ButtonIngreso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ButtonIngreso.setForeground(new java.awt.Color(255, 255, 255));
        ButtonIngreso.setText("Ingresar");
        ButtonIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresoActionPerformed(evt);
            }
        });
        panelRound1.add(ButtonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 280, 30));

        RestaurarPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RestaurarPassword.setForeground(new java.awt.Color(119, 29, 75));
        RestaurarPassword.setText("¿Olvidaste tu contraseña?");
        RestaurarPassword.setToolTipText("");
        RestaurarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RestaurarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RestaurarPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RestaurarPasswordMouseExited(evt);
            }
        });
        panelRound1.add(RestaurarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));
        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        // Para Almacenar, la posicion del mouse en interfaz
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        // Posiscion del mouse en la pantalla 
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation (x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void textExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textExitMouseClicked
        // Cerrar la interfaz
        System.exit(0);
    }//GEN-LAST:event_textExitMouseClicked

    private void textExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textExitMouseEntered
        // Al pasar el mouse cambia de color
        exitBtn.setBackground(new java.awt.Color(171, 56, 93));
        textExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_textExitMouseEntered

    private void textExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textExitMouseExited
        // Retorna al color inicial, al dejar de pasar con el mouse
        exitBtn.setBackground(new java.awt.Color(240, 240, 240));
        textExit.setForeground(new java.awt.Color(187,187,187));
    }//GEN-LAST:event_textExitMouseExited

    private void UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioMousePressed
        
        if (Usuario.getText().equals("Ejemplo: AUT-0000")) {
            Usuario.setText("");
            Usuario.setForeground(Color.black);
        }
        if (String.valueOf(Password.getPassword()).isEmpty()) {
            Password.setText("********");
            Password.setForeground(Color.gray);
        }
    }//GEN-LAST:event_UsuarioMousePressed

    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed
        
        if (String.valueOf(Password.getPassword()).equals("********")) {
            Password.setText("");
            Password.setForeground(Color.black);
        }
        if (Usuario.getText().isEmpty()) {
            Usuario.setText("Ejemplo: AUT-0000");
            Usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PasswordMousePressed

    private void RestaurarPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurarPasswordMouseEntered
        // TODO add your handling code here:
        
        RestaurarPassword.setForeground(new java.awt.Color(171, 56, 93));
    }//GEN-LAST:event_RestaurarPasswordMouseEntered

    private void RestaurarPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurarPasswordMouseExited
        // TODO add your handling code here:
        RestaurarPassword.setForeground(new java.awt.Color(119,29,75));
    }//GEN-LAST:event_RestaurarPasswordMouseExited

    private void ButtonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresoActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * from usuarios WHERE nombre_usuario LIKE ? AND contrasena LIKE ?; ";
        try{
            pst = db.prepareStatement(sql);
            pst.setString(1,Usuario.getText());
            pst.setString(2,Password.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){
                mp.setLogin(this);
                mp.setVisible(true);
                this.setVisible(false);
                Usuario.setText("");
                Password.setText("");
                //JOptionPane.showMessageDialog(null, "Login Correcto");
            }
            else{
                JOptionPane.showMessageDialog(null, "Login Incorrecto");
                Usuario.setText("");
                Password.setText("");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_ButtonIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIngreso;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel RestaurarPassword;
    private javax.swing.JLabel TextPassword;
    private javax.swing.JLabel TextUser;
    private javax.swing.JLabel TituloApp;
    private javax.swing.JTextField Usuario;
    private Interfaces.PanelRound exitBtn;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private Interfaces.PanelRound panelRound1;
    private Interfaces.PanelRound panelRound2;
    private Interfaces.PanelRound panelRound3;
    private Interfaces.PanelRound panelRound4;
    private javax.swing.JLabel textExit;
    // End of variables declaration//GEN-END:variables
}
